// client/src/components/MessageList.tsx
import { useEffect, useRef, useCallback } from "react";
import { useChatStore } from "../stores/chatStore";
import { wsManager } from "../lib/websocket";
import { getAvatarColor, getAvatarInitial, isMoreThan30MinutesApart } from "../lib/avatar";

interface ChatMessage {
  id: number;
  username: string;
  content: string;
  timestamp: Date;
}

function formatTimestamp(date: Date): string {
  const now = new Date();
  const isToday = date.toDateString() === now.toDateString();

  const yesterday = new Date(now);
  yesterday.setDate(yesterday.getDate() - 1);
  const isYesterday = date.toDateString() === yesterday.toDateString();

  const timeStr = date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  if (isToday) {
    return `Today at ${timeStr}`;
  } else if (isYesterday) {
    return `Yesterday at ${timeStr}`;
  } else {
    return `${date.toLocaleDateString([], { month: 'short', day: 'numeric' })} at ${timeStr}`;
  }
}

// Determine if we should show the message header (avatar + username + timestamp)
function shouldShowHeader(
  currentMsg: ChatMessage,
  prevMsg: ChatMessage | null
): boolean {
  // Always show header for first message
  if (!prevMsg) return true;

  // Always show header if different user
  if (currentMsg.username !== prevMsg.username) return true;

  // Always show header for system messages
  if (currentMsg.username === "System") return true;

  // Show header if more than 30 minutes apart
  if (isMoreThan30MinutesApart(currentMsg.timestamp, prevMsg.timestamp)) {
    return true;
  }

  return false;
}

export default function MessageList() {
  const messages = useChatStore((state) => state.messages);
  const hasMoreMessages = useChatStore((state) => state.hasMoreMessages);
  const isLoadingMore = useChatStore((state) => state.isLoadingMore);
  const setLoadingMore = useChatStore((state) => state.setLoadingMore);
  const getOldestMessageId = useChatStore((state) => state.getOldestMessageId);

  const containerRef = useRef<HTMLDivElement>(null);
  const topSentinelRef = useRef<HTMLDivElement>(null);
  const prevMessagesLengthRef = useRef(messages.length);
  const prevScrollHeightRef = useRef(0);

  const bottomRef = useRef<HTMLDivElement>(null);

  // Handle scroll to load more messages
  const handleLoadMore = useCallback(() => {
    if (isLoadingMore || !hasMoreMessages) return;

    const oldestId = getOldestMessageId();
    if (oldestId === null) return;

    // Save scroll height before loading
    if (containerRef.current) {
      prevScrollHeightRef.current = containerRef.current.scrollHeight;
    }

    setLoadingMore(true);
    wsManager.loadMoreMessages(oldestId);
  }, [isLoadingMore, hasMoreMessages, getOldestMessageId, setLoadingMore]);

  // Intersection observer for infinite scroll
  useEffect(() => {
    const sentinel = topSentinelRef.current;
    if (!sentinel) return;

    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMoreMessages && !isLoadingMore) {
          handleLoadMore();
        }
      },
      { threshold: 0.1 }
    );

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [hasMoreMessages, isLoadingMore, handleLoadMore]);

  // Maintain scroll position when prepending messages
  useEffect(() => {
    // Helper to scroll to bottom reliably
    const scrollToBottom = () => {
      bottomRef.current?.scrollIntoView({ behavior: "smooth" });
    };

    if (containerRef.current && messages.length > prevMessagesLengthRef.current) {
      const isInitialLoad = prevMessagesLengthRef.current === 0;
      const isPrepend = messages.length - prevMessagesLengthRef.current > 1;

      // Use requestAnimationFrame to ensure DOM has updated with new messages
      requestAnimationFrame(() => {
        if (containerRef.current) {
          if (isInitialLoad) {
            // Scroll to bottom on initial load (instant)
            bottomRef.current?.scrollIntoView({ behavior: "auto" });
          } else if (isPrepend && prevScrollHeightRef.current > 0) {
            // Maintain scroll position when prepending
            const newScrollHeight = containerRef.current.scrollHeight;
            const scrollDiff = newScrollHeight - prevScrollHeightRef.current;
            containerRef.current.scrollTop = scrollDiff;
          } else {
            // Scroll to bottom for new messages
            scrollToBottom();
          }
        }
      });
    }
    prevMessagesLengthRef.current = messages.length;
  }, [messages]);

  return (
    <div ref={containerRef} className="flex-1 overflow-y-auto px-4 py-2 h-full">
      {/* Top sentinel for infinite scroll */}
      <div ref={topSentinelRef} className="h-1" />

      {/* Loading indicator */}
      {isLoadingMore && (
        <div className="flex justify-center py-4">
          <div className="text-chad-muted text-sm">Loading older messages...</div>
        </div>
      )}

      {/* No more messages indicator */}
      {!hasMoreMessages && messages.length > 0 && (
        <div className="flex justify-center py-4 mb-4">
          <div className="text-chad-muted text-xs">This is the beginning of the conversation</div>
        </div>
      )}

      {messages.length === 0 && !isLoadingMore ? (
        <div className="flex items-center justify-center h-full text-chad-muted">
          No messages yet. Start the conversation!
        </div>
      ) : (
        messages.map((msg, index) => {
          const prevMsg = index > 0 ? messages[index - 1] : null;
          const showHeader = shouldShowHeader(msg, prevMsg);
          const isSystem = msg.username === "System";

          if (isSystem) {
            return (
              <div key={msg.id} className="py-1 px-4 text-center">
                <span className="text-xs text-chad-muted">{msg.content}</span>
                <span className="text-xs text-chad-muted ml-2">
                  {formatTimestamp(msg.timestamp)}
                </span>
              </div>
            );
          }

          return (
            <div
              key={msg.id}
              className={`group flex gap-4 py-0.5 px-2 hover:bg-chad-bg-hover rounded ${
                showHeader ? "mt-4" : ""
              }`}
            >
              {/* Avatar column - show avatar only on header rows */}
              <div className="w-10 flex-shrink-0">
                {showHeader && (
                  <div
                    className={`w-10 h-10 rounded-full ${getAvatarColor(
                      msg.username
                    )} flex items-center justify-center text-sm font-medium text-white`}
                  >
                    {getAvatarInitial(msg.username)}
                  </div>
                )}
              </div>

              {/* Message content */}
              <div className="flex-1 min-w-0">
                {showHeader && (
                  <div className="flex items-baseline gap-2">
                    <span className="font-medium text-chad-steel hover:underline cursor-pointer">
                      {msg.username}
                    </span>
                    <span className="text-xs text-chad-muted">
                      {formatTimestamp(msg.timestamp)}
                    </span>
                  </div>
                )}
                <div className="text-chad-platinum leading-relaxed break-words">
                  {msg.content}
                </div>
              </div>
            </div>
          );
        })
      )}
      {/* Bottom sentinel for auto-scroll */}
      <div ref={bottomRef} />
    </div>
  );
}

// client/src/components/MessageList.svelte
<script lang="ts">
  import { onDestroy, onMount } from "svelte";
  import { getAvatarColor, getAvatarInitial, isMoreThan30MinutesApart } from "../lib/avatar";
  import { wsManager } from "../lib/websocket";
  import {
    chatState,
    getOldestMessageId,
    setLoadingMore,
    type ChatMessage,
  } from "../stores/chat.svelte";

  let containerRef: HTMLDivElement | null = null;
  let topSentinelRef: HTMLDivElement | null = null;
  let bottomRef: HTMLDivElement | null = null;

  let previousMessagesLength = 0;
  let previousScrollHeight = 0;
  let observer: IntersectionObserver | null = null;

  function formatTimestamp(date: Date): string {
    const now = new Date();
    const isToday = date.toDateString() === now.toDateString();

    const yesterday = new Date(now);
    yesterday.setDate(yesterday.getDate() - 1);
    const isYesterday = date.toDateString() === yesterday.toDateString();

    const time = date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

    if (isToday) {
      return `Today at ${time}`;
    }
    if (isYesterday) {
      return `Yesterday at ${time}`;
    }
    return `${date.toLocaleDateString([], { month: "short", day: "numeric" })} at ${time}`;
  }

  function shouldShowHeader(currentMessage: ChatMessage, previousMessage: ChatMessage | null): boolean {
    if (!previousMessage) {
      return true;
    }
    if (currentMessage.username !== previousMessage.username) {
      return true;
    }
    if (currentMessage.username === "System") {
      return true;
    }
    return isMoreThan30MinutesApart(currentMessage.timestamp, previousMessage.timestamp);
  }

  function handleLoadMore(): void {
    if ($chatState.isLoadingMore || !$chatState.hasMoreMessages) {
      return;
    }

    const oldestMessageId = getOldestMessageId();
    if (oldestMessageId === null) {
      return;
    }

    if (containerRef) {
      previousScrollHeight = containerRef.scrollHeight;
    }

    setLoadingMore(true);
    wsManager.loadMoreMessages(oldestMessageId);
  }

  function scrollToBottom(behavior: ScrollBehavior): void {
    bottomRef?.scrollIntoView({ behavior });
  }

  $: {
    const currentLength = $chatState.messages.length;
    if (currentLength > previousMessagesLength && containerRef) {
      const isInitialLoad = previousMessagesLength === 0;
      const isPrepend = currentLength - previousMessagesLength > 1;

      requestAnimationFrame(() => {
        if (!containerRef) {
          return;
        }

        if (isInitialLoad) {
          scrollToBottom("auto");
        } else if (isPrepend && previousScrollHeight > 0) {
          const nextScrollHeight = containerRef.scrollHeight;
          const scrollDelta = nextScrollHeight - previousScrollHeight;
          containerRef.scrollTop = scrollDelta;
        } else {
          scrollToBottom("smooth");
        }
      });
    }

    previousMessagesLength = currentLength;
  }

  onMount(() => {
    if (!topSentinelRef) {
      return;
    }

    observer = new IntersectionObserver(
      (entries) => {
        if (entries[0]?.isIntersecting) {
          handleLoadMore();
        }
      },
      { threshold: 0.1 }
    );

    observer.observe(topSentinelRef);
  });

  onDestroy(() => {
    observer?.disconnect();
  });
</script>

<div bind:this={containerRef} class="flex-1 overflow-y-auto px-4 py-2 h-full">
  <div bind:this={topSentinelRef} class="h-1"></div>

  {#if $chatState.isLoadingMore}
    <div class="flex justify-center py-4">
      <div class="text-chad-muted text-sm">Loading older messages...</div>
    </div>
  {/if}

  {#if !$chatState.hasMoreMessages && $chatState.messages.length > 0}
    <div class="flex justify-center py-4 mb-4">
      <div class="text-chad-muted text-xs">This is the beginning of the conversation</div>
    </div>
  {/if}

  {#if $chatState.messages.length === 0 && !$chatState.isLoadingMore}
    <div class="flex items-center justify-center h-full text-chad-muted">No messages yet. Start the conversation!</div>
  {:else}
    {#each $chatState.messages as message, index (message.id)}
      {@const previousMessage = index > 0 ? $chatState.messages[index - 1] : null}
      {@const showHeader = shouldShowHeader(message, previousMessage)}
      {@const isSystem = message.username === "System"}

      {#if isSystem}
        <div class="py-1 px-4 text-center">
          <span class="text-xs text-chad-muted">{message.content}</span>
          <span class="text-xs text-chad-muted ml-2">{formatTimestamp(message.timestamp)}</span>
        </div>
      {:else}
        <div class={`group flex gap-4 py-0.5 px-2 hover:bg-chad-bg-hover rounded ${showHeader ? "mt-4" : ""}`}>
          <div class="w-10 flex-shrink-0">
            {#if showHeader}
              <div
                class={`w-10 h-10 rounded-full ${getAvatarColor(message.username)} flex items-center justify-center text-sm font-medium text-white`}
              >
                {getAvatarInitial(message.username)}
              </div>
            {/if}
          </div>

          <div class="flex-1 min-w-0">
            {#if showHeader}
              <div class="flex items-baseline gap-2">
                <span class="font-medium text-chad-steel hover:underline cursor-pointer">{message.username}</span>
                <span class="text-xs text-chad-muted">{formatTimestamp(message.timestamp)}</span>
              </div>
            {/if}
            <div class="text-chad-platinum leading-relaxed break-words">{message.content}</div>
          </div>
        </div>
      {/if}
    {/each}
  {/if}

  <div bind:this={bottomRef}></div>
</div>
